# Generated by Django 5.2.9 on 2025-12-11 06:19

import django.db.models.deletion
import game.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room_id",
                    models.CharField(
                        default=game.models.generate_room_id, max_length=6, unique=True
                    ),
                ),
                ("creator_id", models.BigIntegerField()),
                ("creator_name", models.CharField(max_length=100)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Легкий"),
                            ("medium", "Средний"),
                            ("hard", "Сложный"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_game_started", models.BooleanField(default=False)),
                ("current_round", models.IntegerField(default=1)),
                (
                    "current_team",
                    models.CharField(
                        choices=[("A", "Команда A"), ("B", "Команда B")],
                        default="A",
                        max_length=1,
                    ),
                ),
                ("current_explainer_index", models.IntegerField(default=0)),
                ("current_guesser_index", models.IntegerField(default=1)),
                ("words_used", models.TextField(default="[]")),
                ("score_a", models.IntegerField(default=0)),
                ("score_b", models.IntegerField(default=0)),
                ("target_score", models.IntegerField(default=25)),
                ("time_per_turn", models.IntegerField(default=60)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.BigIntegerField()),
                ("username", models.CharField(max_length=100)),
                (
                    "team",
                    models.CharField(
                        choices=[("A", "Команда A"), ("B", "Команда B")], max_length=1
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="game.gameroom",
                    ),
                ),
            ],
            options={
                "unique_together": {("room", "user_id")},
            },
        ),
    ]
